### PR TITLE
Update/user service--Done

### PR DESCRIPTION
**Pull request by kevinburnside**
I believe the userService is mostly done, now you can get the users details from storage. If we need any other functions added to userService please suggest..

### CODE REVIEW

**Comment by aagavin** [comment]
Hey @kevinburnside your branch conflicts

**Comment by kevinburnside** [comment]
Fixed, hopefully it didnt break anything!

**Comment by aagavin** [comment]
Looks good

**Review by aagavin — DISMISSED** [review]
Looks good

**Comment by aagavin** [comment]
@kevinburnside  Have you used async await?

**Review by aagavin — APPROVED** [review]

**Pull request merged**
